skip_non_tags: true

image: Visual Studio 2022

# - SignPath の Trusted Build System を使うために /appveyor.yml に配置している
#   https://about.signpath.io/documentation/trusted-build-systems/appveyor

# - AppVeyor のプロジェクトの Settings - Environment に TT_VERSION の設定が必要
#   buildtools\svnrev\sourcetree_info.bat で自動生成したものを読み込めないので別に設定が必要

environment:
# リリースではキャッシュを使わない
# APPVEYOR_SAVE_CACHE_ON_ERROR: true
  VS_VERSION: 2022
  NOPAUSE: 1
  # SignPath
  ORGANIZATION_ID: 78e41f48-55fc-4f33-8ea5-08ac32f65ac8
  PROJECT_SLUG: teraterm
  SIGNING_POLICY_SLUG: test-signing
  ARTIFACT_CONFIGURATION_SLUG: teraterm-%TT_VERSION%

for:
  -
    branches:
      only:
        - main
    environment:
      SIGNPATH_SIGNING_POLICY_SLUG: release-signing

build: off

init:
  # 実行している yml を表示
  - echo appveyor.yml
  # タイムゾーンを JST に変更
  - tzutil /s "Tokyo Standard Time"

# リリースではキャッシュを使わない
# cache:
#   - libs

before_build:
  # インストール済みの Cygwin を更新
  # - ci_scripts/upgrade_syscygwin.bat
  # インストール済みの Cygwin にパッケージを追加
  - ci_scripts/addpkg_syscygwin.bat
  # インストール済みの MSYS2 にパッケージを追加
  # - ci_scripts/addpkg_msys2.bat
  # 自前の Cygwin をインストール
  # - buildtools/install_cygwin.bat
  # 自前の Inno Setup をインストール
  - buildtools/install_innosetup.bat

build_script:
  - ci_scripts/build_appveyor_release_bat.bat

after_build:
  # ソース管理しているファイルがキャッシュされて更新されなくなるのを防ぐため削除
  - ci_scripts/build_appveyor_release_bat_pre_cache.bat
  # 署名用スクリプトをコピーする
  - ps: (Get-Content ci_scripts/create_installer.ps1) -replace 'TT_VERSION', "%TT_VERSION%" | Set-Content installer/Output/create_installer.ps1

artifacts:
  - path: installer/Output/*.zip
  - path: installer/teraterm.iss
  - path: installer/Output/create_installer.ps1

# SignPath Trusted Build System
deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/%ORGANIZATION_ID%/Integrations/AppVeyor?ProjectSlug=%PROJECT_SLUG%&SigningPolicySlug=%SIGNING_POLICY_SLUG%&ArtifactConfigurationSlug=%ARTIFACT_CONFIGURATION_SLUG%
  authorization:
    secure: iS8DOdESKomXlP8LpnfThhapFMdeJJ0M0Rw+h2XwcFLGAUfHz52tHaTAVmH4yE+nePb6n5YxmvqpI39O+acZMw==

# AppVeyor のプロジェクトの Settings - Environment に WEBHOOK_URL を設定するかどうかで制御する
# on_success:
#   - ci_scripts\notify.bat success
# on_failure:
#   - ci_scripts\notify.bat failure

on_finish:
# ビルド完了後に RDP が有効になる。blockRdp を指定しているので、完了後にも終了しない。
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
